<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nextPage</name>
   <tag></tag>
   <elementGuidId>a7ab6914-4df2-49e0-9270-efd2deed0d8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[7]/div[3]/div[1]/div[2]/div/div[11]/div[3]/div[3]/form/div/div[1]/div[8]/div[1]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
