<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_click_year_cart</name>
   <tag></tag>
   <elementGuidId>df402552-55f2-415e-a683-ef7f73f0ea68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;payment_method&quot;]/div[2]/div[3]/div[2]/table/tbody/tr[1]/td[3]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method&quot;)/div[@class=&quot;method&quot;]/div[@class=&quot;method_content method_content_2&quot;]/div[@class=&quot;card_info&quot;]/table[1]/tbody[1]/tr[1]/td[3]/div[@class=&quot;input_wrapper year pay_select_container select_option&quot;]/div[@class=&quot;chosen-container chosen-container-single chosen-container-single-nosearch chosen-container-active chosen-with-drop&quot;]/a[@class=&quot;chosen-single&quot;]/div[1]/b[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment_method']/div[2]/div[3]/div[2]/table/tbody/tr/td[3]/div/div/a/div/b</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/a/div/b</value>
   </webElementXpaths>
</WebElementEntity>
