<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>optional_bill_apartment</name>
   <tag></tag>
   <elementGuidId>5bbacbea-97ba-4313-abcd-6bf1c82a8ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;checkout_edit_form&quot;]/div/div[2]/div[1]/div[1]/div[2]/div/div[6]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
