<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>optional_bill_company</name>
   <tag></tag>
   <elementGuidId>10aeeee2-3dcf-4f13-a223-275575c9c242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;checkout_edit_form&quot;]/div/div[2]/div[1]/div[1]/div[2]/div/div[3]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
