<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_year_test</name>
   <tag></tag>
   <elementGuidId>ac228cd8-ba83-43c7-9739-f51791507c02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;payment_method&quot;]/div[2]/div[3]/div[2]/table/tbody/tr[1]/td[3]/div/div/div/ul</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
